/**
 * @file server.js
 * @description Main application entry point and Express backend server for PoultryDSS.
 * Handles API routing for configurations, proposals, batches, daily logs, transactions, and completed snapshots.
 * Integrates an automated background synchronization loop for environmental telemetry from the Tuya Cloud API.
 * Configured with strict CORS origin verification and static file path directory traversal guards.
 */

const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const { runQuery, allQuery, getQuery } = require('./db');

const app = express();
const PORT = process.env.PORT || 80;

/**
 * Configure Cross-Origin Resource Sharing (CORS) with LAN-subnet and loopback restrictions.
 * Blocks unauthorized remote requests while allowing connections from localhost, local subnet IPs (192.168.x.x),
 * and Tailscale VPN IPs (10.x.x.x) for cross-device synchronization on the farm.
 */
app.use(cors({
    origin: (origin, callback) => {
        if (!origin) return callback(null, true);
        const isLocalhost = /^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);
        const isLan = /^http:\/\/(192\.168\.\d+\.\d+|10\.\d+\.\d+\.\d+)(:\d+)?$/.test(origin);
        if (isLocalhost || isLan) {
            callback(null, true);
        } else {
            callback(new Error('Not allowed by CORS'));
        }
    }
}));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

/**
 * Middleware: Intercepts and blocks unauthorized access to sensitive backend source code,
 * configuration files, local databases, testing scripts, and Git directories.
 * Normalizes request paths to prevent directory traversal bypasses.
 */
app.use((req, res, next) => {
    const blockedFiles = [
        'server.js', 'db.js', '.env', 'package.json', 'package-lock.json',
        'Dockerfile', 'docker-compose.yml', 'deploy.sh', '.gitignore', 'README.md'
    ];
    const blockedDirs = ['/data', '/tests', '/.git', '/scripts', '/docs', '/scratch'];
    
    // Normalize request path to prevent traversal bypass
    const reqPath = path.normalize(req.path).replace(/^(\.\.(\/|\\|$))+/, '');
    const filename = path.basename(reqPath);
    
    const isBlockedFile = blockedFiles.some(f => filename.toLowerCase() === f.toLowerCase());
    const isBlockedDir = blockedDirs.some(d => reqPath.toLowerCase().startsWith(d));
    
    if (isBlockedFile || isBlockedDir) {
        return res.status(403).json({ error: 'Access denied' });
    }
    next();
});

/**
 * Route: Serves the Service Worker script with cache-control headers disabled.
 * Ensures clients always reload the latest service worker for offline operations.
 */
app.get('/service-worker.js', (req, res) => {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
    res.sendFile(path.join(__dirname, 'service-worker.js'));
});

/**
 * Route: Serves Javascript asset files with cache-control headers disabled.
 * Prevents clients caching stale script logic during updates.
 */
app.get('/js/:file', (req, res) => {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
    res.sendFile(path.join(__dirname, 'js', req.params.file));
});

// Expose public folder static files with hidden dotfiles blocked
app.use(express.static(__dirname, { index: 'index.html', dotfiles: 'deny' }));

/**
 * Helper: Normalizes batch and proposal IDs by stripping floating-point suffixes (.0)
 * generated by Excel/CSV sheet imports.
 * @param {string|number} id - Raw database identifier.
 * @returns {string} Clean string representation of the ID.
 */
const normalizeId = (id) => id ? String(id).replace(/\.0$/, '') : id;

/**
 * Middleware: Confirms the presence of the `x-confirm-delete` safety header
 * before allowing bulk delete database queries to prevent accidental truncation.
 */
const requireConfirm = (req, res, next) => {
    if (req.headers['x-confirm-delete'] !== 'true') {
        return res.status(403).json({ error: 'Missing x-confirm-delete header for bulk operation.' });
    }
    next();
};

/**
 * Middleware: Ensures the request body contains a valid, non-empty JSON payload.
 */
const validateBody = (req, res, next) => {
    if (!req.body || typeof req.body !== 'object' || Object.keys(req.body).length === 0) {
        return res.status(400).json({ error: 'Invalid or empty JSON body' });
    }
    next();
};


// ===================== ENTITIES (Farm Profile, Aggregates) =====================

/**
 * GET /api/entities/:key
 * Retrieves a key-value store entry from the entities table.
 * Used for storing general settings, farm profiles, and historical aggregates.
 */
app.get('/api/entities/:key', async (req, res) => {
    try {
        const row = await getQuery('SELECT value FROM entities WHERE key = ?', [req.params.key]);
        res.json(row ? JSON.parse(row.value) : null);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/entities/:key
 * Inserts or updates a key-value store entry.
 */
app.post('/api/entities/:key', validateBody, async (req, res) => {
    try {
        await runQuery('INSERT INTO entities (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP', [req.params.key, JSON.stringify(req.body.value)]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== PROPOSALS =====================

/**
 * GET /api/proposals
 * Retrieves all saved economic investment proposals.
 */
app.get('/api/proposals', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM proposals');
        res.json(rows.map(r => JSON.parse(r.data)));
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/proposals
 * Inserts or updates a financial investment proposal.
 */
app.post('/api/proposals', validateBody, async (req, res) => {
    try {
        const proposal = req.body;
        await runQuery('INSERT INTO proposals (id, data, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP', [proposal.id, JSON.stringify(proposal)]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/proposals/:id
 * Deletes a proposal by unique ID (stripping import float decimals).
 */
app.delete('/api/proposals/:id', async (req, res) => {
    try {
        const id = normalizeId(req.params.id);
        await runQuery('DELETE FROM proposals WHERE id = ? OR id = ?', [id, id + '.0']);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/proposals
 * Bulk clear ALL proposals. Requires safety confirmation header.
 */
app.delete('/api/proposals', requireConfirm, async (req, res) => {
    try {
        await runQuery('DELETE FROM proposals');
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== BATCHES =====================

/**
 * GET /api/batches
 * Retrieves all cohort batches (active and archived).
 */
app.get('/api/batches', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM batches');
        res.json(rows.map(r => JSON.parse(r.data)));
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/batches
 * Inserts or updates a flock cohort batch config.
 */
app.post('/api/batches', validateBody, async (req, res) => {
    try {
        const batch = req.body;
        const id = normalizeId(batch.id);
        batch.id = id;
        await runQuery('INSERT INTO batches (id, data, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP', [id, JSON.stringify(batch)]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/batches/:id
 * Deletes a specific batch and purges all logs, transactions, and health records linked to it.
 */
app.delete('/api/batches/:id', async (req, res) => {
    try {
        const id = normalizeId(req.params.id);
        await runQuery('DELETE FROM batches WHERE id = ? OR id = ?', [id, id + '.0']);
        // Cascade delete all operational logs for this batch
        await runQuery('DELETE FROM logs WHERE batch_id = ? OR batch_id = ?', [id, id + '.0']);
        await runQuery('DELETE FROM transactions WHERE batch_id = ? OR batch_id = ?', [id, id + '.0']);
        await runQuery('DELETE FROM health_logs WHERE batch_id = ? OR batch_id = ?', [id, id + '.0']);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/batches
 * Bulk clears all batch records and operational logs. Requires safety confirmation header.
 */
app.delete('/api/batches', requireConfirm, async (req, res) => {
    try {
        await runQuery('DELETE FROM batches');
        await runQuery('DELETE FROM logs');
        await runQuery('DELETE FROM transactions');
        await runQuery('DELETE FROM health_logs');
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== SNAPSHOTS =====================

/**
 * GET /api/snapshots
 * Retrieves completed historical cohort snapshots.
 */
app.get('/api/snapshots', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM snapshots');
        res.json(rows.map(r => JSON.parse(r.data)));
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/snapshots
 * Saves a completed flock batch cohort snapshot.
 */
app.post('/api/snapshots', validateBody, async (req, res) => {
    try {
        const snapshot = req.body;
        await runQuery('INSERT INTO snapshots (id, data, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP', [snapshot.id, JSON.stringify(snapshot)]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/snapshots/:id
 * Deletes a specific batch snapshot by ID.
 */
app.delete('/api/snapshots/:id', async (req, res) => {
    try {
        await runQuery('DELETE FROM snapshots WHERE id = ?', [req.params.id]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/snapshots
 * Truncates all snapshots. Requires safety confirmation header.
 */
app.delete('/api/snapshots', requireConfirm, async (req, res) => {
    try {
        await runQuery('DELETE FROM snapshots');
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== OPERATIONAL LOGS =====================

/**
 * GET /api/logs/:batchId
 * Retrieves all daily tracking records for a specific cohort, sorted newest first.
 */
app.get('/api/logs/:batchId', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM logs WHERE batch_id = ? ORDER BY date DESC', [req.params.batchId]);
        res.json(rows.map(r => JSON.parse(r.data)));
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/logs/:batchId
 * Saves a daily tracking record (eggs, feed, mortality, etc.).
 */
app.post('/api/logs/:batchId', async (req, res) => {
    try {
        const log = req.body;
        const id = log.id || `${req.params.batchId}_${log.date}`; // enforce unique compound id
        log.id = id;
        await runQuery('INSERT INTO logs (id, batch_id, data, date, updated_at) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP', [id, req.params.batchId, JSON.stringify(log), log.date]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/logs/:batchId/:id
 * Deletes a single daily log entry.
 */
app.delete('/api/logs/:batchId/:id', async (req, res) => {
    try {
        await runQuery('DELETE FROM logs WHERE batch_id = ? AND id = ?', [req.params.batchId, req.params.id]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/logs/:batchId
 * Clears all daily logs associated with a specific batch.
 */
app.delete('/api/logs/:batchId', async (req, res) => {
    try {
        const id = req.params.batchId;
        await runQuery('DELETE FROM logs WHERE batch_id = ? OR batch_id = ?', [id, id + '.0']);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== FINANCIAL TRANSACTIONS =====================

/**
 * GET /api/transactions/:batchId
 * Retrieves all ledger transactions (cost, revenue) recorded for a cohort.
 */
app.get('/api/transactions/:batchId', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM transactions WHERE batch_id = ?', [req.params.batchId]);
        res.json(rows.map(r => JSON.parse(r.data)));
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/transactions/:batchId
 * Saves a cost or revenue transaction to the ledger.
 */
app.post('/api/transactions/:batchId', async (req, res) => {
    try {
        const tx = req.body;
        const id = tx.id || `${req.params.batchId}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
        tx.id = id;
        await runQuery('INSERT INTO transactions (id, batch_id, data, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP', [id, req.params.batchId, JSON.stringify(tx)]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/transactions/:batchId/:id
 * Deletes a ledger transaction.
 */
app.delete('/api/transactions/:batchId/:id', async (req, res) => {
    try {
        await runQuery('DELETE FROM transactions WHERE batch_id = ? AND id = ?', [req.params.batchId, req.params.id]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * DELETE /api/transactions/:batchId
 * Clears all transactions for a specific batch.
 */
app.delete('/api/transactions/:batchId', async (req, res) => {
    try {
        const id = req.params.batchId;
        await runQuery('DELETE FROM transactions WHERE batch_id = ? OR batch_id = ?', [id, id + '.0']);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== HEALTH RECORDS =====================

/**
 * GET /api/health/:batchId
 * Retrieves all health logs (vaccinations, dewormers, medications) for a batch.
 */
app.get('/api/health/:batchId', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM health_logs WHERE batch_id = ? ORDER BY updated_at DESC', [req.params.batchId]);
        res.json(rows.map(r => JSON.parse(r.data)));
    } catch (e) { res.status(500).json({ error: e.message }); }
});

/**
 * POST /api/health/:batchId
 * Records a new flock health event.
 */
app.post('/api/health/:batchId', async (req, res) => {
    try {
        const log = req.body;
        const id = log.id || `${req.params.batchId}_h_${Date.now()}`;
        log.id = id;
        await runQuery('INSERT INTO health_logs (id, batch_id, data, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP', [id, req.params.batchId, JSON.stringify(log)]);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== EXPORTS =====================

/**
 * GET /api/export/:batchId
 * Compiles and returns a CSV file download of all daily logs recorded for a batch.
 */
app.get('/api/export/:batchId', async (req, res) => {
    try {
        const rows = await allQuery('SELECT data FROM logs WHERE batch_id = ? ORDER BY date ASC', [req.params.batchId]);
        if (!rows.length) {
            return res.status(404).send('No logs found for this batch');
        }
        
        const logs = rows.map(r => JSON.parse(r.data));
        const headers = ['date', 'eggs', 'mortality', 'feed', 'sacks', 'notes'];
        
        // Assemble CSV output string
        let csv = headers.join(',') + '\n';
        logs.forEach(log => {
            const row = headers.map(h => {
                let val = log[h] !== undefined ? log[h] : '';
                if (typeof val === 'string') {
                    val = val.replace(/"/g, '""');
                    if (val.includes(',') || val.includes('\n')) {
                        val = `"${val}"`;
                    }
                }
                return val;
            });
            csv += row.join(',') + '\n';
        });

        res.header('Content-Type', 'text/csv');
        res.attachment(`batch_${req.params.batchId}_export.csv`);
        res.send(csv);
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// ===================== TUYA CLOUD INTEGRATION =====================

// Load environment configurations locally if .env file exists
const dotenvPath = path.join(__dirname, '.env');
if (fs.existsSync(dotenvPath)) {
    const envConfig = fs.readFileSync(dotenvPath, 'utf8');
    envConfig.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
            const parts = trimmed.split('=');
            const key = parts[0].trim();
            const value = parts.slice(1).join('=').trim();
            if (key && value && !process.env[key]) {
                process.env[key] = value;
            }
        }
    });
}

const https = require('https');
const crypto = require('crypto');

/**
 * Tuya-compliant API authorization signature generator (HMAC-SHA256).
 * Shared by all Tuya Cloud requests (live sync and historical lookups).
 */
function tuyaSign(clientId, secret, t, nonce, stringToSign, accessToken = '') {
    const str = accessToken
        ? clientId + accessToken + t + nonce + stringToSign
        : clientId + t + nonce + stringToSign;
    return crypto.createHmac('sha256', secret).update(str, 'utf8').digest('hex').toUpperCase();
}

/**
 * Dispatches a signed HTTPS request to the Tuya Cloud API gateway.
 * Shared by all Tuya Cloud requests (live sync and historical lookups).
 */
function tuyaRequest(baseUrl, clientId, secret, method, path, body = null, accessToken = '') {
    return new Promise((resolve, reject) => {
        const t = Date.now().toString();
        const nonce = crypto.randomUUID();
        const bodyStr = body ? JSON.stringify(body) : '';
        const contentHash = crypto.createHash('sha256').update(bodyStr, 'utf8').digest('hex');

        // Parse and sort query parameters alphabetically by key to satisfy Tuya's signature requirements.
        let signedPath = path;
        const queryIndex = path.indexOf('?');
        if (queryIndex !== -1) {
            const pathname = path.substring(0, queryIndex);
            const queryStr = path.substring(queryIndex + 1);
            const pairs = queryStr.split('&').map(pair => {
                const idx = pair.indexOf('=');
                if (idx === -1) return [pair, ''];
                return [pair.substring(0, idx), pair.substring(idx + 1)];
            });
            pairs.sort((a, b) => a[0].localeCompare(b[0]));
            const sortedQs = pairs.map(([key, val]) => `${key}=${val}`).join('&');
            signedPath = pathname + '?' + sortedQs;
        }

        const stringToSign = `${method}\n${contentHash}\n\n${signedPath}`;
        const signature = tuyaSign(clientId, secret, t, nonce, stringToSign, accessToken);

        const headers = {
            'client_id': clientId,
            'sign': signature,
            't': t,
            'sign_method': 'HMAC-SHA256',
            'nonce': nonce,
            'Content-Type': 'application/json'
        };
        if (accessToken) headers['access_token'] = accessToken;

        const req = https.request({
            hostname: baseUrl,
            port: 443,
            path: signedPath,
            method: method,
            headers: headers
        }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try {
                    resolve(JSON.parse(data));
                } catch (e) {
                    reject(new Error(`Invalid JSON: ${data}`));
                }
            });
        });
        req.on('error', reject);
        if (bodyStr) req.write(bodyStr);
        req.end();
    });
}

/**
 * Reads Tuya credentials from environment variables.
 * @returns {Object|null} Config object ({clientId, secret, deviceId, region, baseUrl}), or null if not fully configured.
 */
function getTuyaConfig() {
    const clientId = process.env.TUYA_CLIENT_ID;
    const secret = process.env.TUYA_CLIENT_SECRET;
    const deviceId = process.env.TUYA_DEVICE_ID;
    const region = process.env.TUYA_REGION || 'eu';

    if (!clientId || !secret || !deviceId) return null;

    return { clientId, secret, deviceId, region, baseUrl: `openapi.tuya${region}.com` };
}

let cachedTuyaToken = null;
let tuyaTokenExpiry = 0; // ms epoch

/**
 * Fetches a fresh Tuya Cloud access token for the given config, with in-memory caching.
 * @param {Object} cfg - Config object from getTuyaConfig().
 * @returns {Promise<string>} The access token.
 */
async function getTuyaAccessToken(cfg) {
    const now = Date.now();
    // Reuse cached token if it has at least 5 minutes left
    if (cachedTuyaToken && tuyaTokenExpiry > now + 5 * 60 * 1000) {
        return cachedTuyaToken;
    }

    const tokenRes = await tuyaRequest(cfg.baseUrl, cfg.clientId, cfg.secret, 'GET', '/v1.0/token?grant_type=1');
    if (!tokenRes.success) {
        const err = new Error(`Token request failed: ${tokenRes.msg || tokenRes.code}`);
        err.apiCode = tokenRes.code;
        err.apiRaw  = tokenRes;
        throw err;
    }
    
    cachedTuyaToken = tokenRes.result.access_token;
    const expiresSeconds = parseInt(tokenRes.result.expire_time) || 7200;
    tuyaTokenExpiry = Date.now() + expiresSeconds * 1000;
    
    return cachedTuyaToken;
}

/**
 * Triggers a background sync operation requesting live telemetry values from the Tuya Cloud API.
 * Authenticates using client credentials and signatures (HMAC-SHA256), parses va_temperature/va_humidity,
 * caches values to local SQLite, and dispatches an auto-fill request for today's logs.
 * @returns {Promise<void>}
 */
async function syncTuyaSensor() {
    const cfg = getTuyaConfig();
    if (!cfg) {
        console.log('Tuya Sync: credentials not fully configured in environment.');
        return;
    }

    try {
        console.log('Tuya Sync: Fetching access token...');
        const accessToken = await getTuyaAccessToken(cfg);

        console.log('Tuya Sync: Fetching device status...');
        const statusRes = await tuyaRequest(cfg.baseUrl, cfg.clientId, cfg.secret, 'GET', `/v1.0/devices/${cfg.deviceId}/status`, null, accessToken);

        if (!statusRes.success) {
            const err = new Error(`Device status request failed: ${statusRes.msg || statusRes.code}`);
            err.apiCode = statusRes.code;
            err.apiRaw  = statusRes;
            throw err;
        }

        let temperature = null;
        let humidity = null;
        let battery = null;

        if (statusRes.result && Array.isArray(statusRes.result)) {
            statusRes.result.forEach(item => {
                const val = item.value;
                if (item.code === 'va_temperature') {
                    // Adjust 3-digit scaling integer sometimes sent by Tuya sensors (e.g. 250 -> 25.0°C)
                    temperature = typeof val === 'number' && val > 100 ? val / 10 : val;
                } else if (item.code === 'va_humidity') {
                    humidity = typeof val === 'number' && val > 100 ? val / 10 : val;
                } else if (item.code === 'battery_percentage') {
                    battery = val;
                }
            });
        }

        const sensorData = {
            temperature,
            humidity,
            battery,
            last_updated: new Date().toISOString(),
            success: true
        };

        console.log('Tuya Sync: Success, parsed data:', sensorData);
        await runQuery(
            'INSERT INTO entities (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP',
            ['live_sensors', JSON.stringify(sensorData)]
        );

        // Update today's daily log with fetched data
        await autoFillTodayLog(sensorData);

    } catch (err) {
        console.error('Tuya Sync failed:', err.message, err.apiRaw || '');

        const row = await getQuery('SELECT value FROM entities WHERE key = ?', ['live_sensors']);
        let cached = row ? JSON.parse(row.value) : {};
        cached.success      = false;
        cached.error        = err.message;
        cached.error_code   = err.apiCode   || null;
        cached.error_raw    = err.apiRaw    || null;
        cached.last_attempt = new Date().toISOString();

        await runQuery(
            'INSERT INTO entities (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP',
            ['live_sensors', JSON.stringify(cached)]
        );
    }
}

/**
 * Fetches and aggregates Tuya device-reported temperature/humidity for a given calendar date,
 * for backfilling daily logs that were missed (e.g. logged later from paper notes).
 *
 * Uses the Tuya Cloud "Query device logs" endpoint (type=7: data point reports), which on the
 * free edition retains the last 7 days of history. The date is interpreted in East Africa Time
 * (UTC+3) to match how daily logs are keyed elsewhere in the app.
 *
 * @param {string} dateStr - Date in YYYY-MM-DD format (EAT).
 * @returns {Promise<Object>} { success, date, temperature: {avg,min,max,count}|null, humidity: {avg,min,max,count}|null }
 *                            or { success: false, error, error_code? } on failure.
 */
async function fetchTuyaSensorHistory(dateStr) {
    const cfg = getTuyaConfig();
    if (!cfg) {
        return { success: false, error: 'Tuya credentials not configured' };
    }

    // East Africa Time is UTC+3; resolve the local day's boundaries to 13-digit ms timestamps.
    const startTime = new Date(`${dateStr}T00:00:00+03:00`).getTime();
    if (isNaN(startTime)) {
        return { success: false, error: 'Invalid date format, expected YYYY-MM-DD' };
    }
    const endTime = startTime + (24 * 60 * 60 * 1000) - 1;

    try {
        const accessToken = await getTuyaAccessToken(cfg);

        const readings = { va_temperature: [], va_humidity: [] };
        let rowKey = '';
        let hasNext = true;
        let pages = 0;

        // Free edition: type=7 (data point reported to cloud), paginated via row keys.
        // Cap pagination as a sanity limit against runaway loops.
        while (hasNext && pages < 20) {
            const qs = `codes=va_temperature,va_humidity&type=7&start_time=${startTime}&end_time=${endTime}&size=100&query_type=1&start_row_key=${encodeURIComponent(rowKey)}`;
            const logRes = await tuyaRequest(cfg.baseUrl, cfg.clientId, cfg.secret, 'GET', `/v1.0/devices/${cfg.deviceId}/logs?${qs}`, null, accessToken);

            if (!logRes.success) {
                const err = new Error(`Device log request failed: ${logRes.msg || logRes.code}`);
                err.apiCode = logRes.code;
                err.apiRaw  = logRes;
                throw err;
            }

            const logs = (logRes.result && logRes.result.logs) || [];
            for (const entry of logs) {
                const raw = parseFloat(entry.value);
                if (isNaN(raw)) continue;
                // Same 3-digit scaling fix as the live sync (e.g. 250 -> 25.0°C)
                const val = Math.abs(raw) > 100 ? raw / 10 : raw;
                if (entry.code === 'va_temperature') readings.va_temperature.push(val);
                else if (entry.code === 'va_humidity') readings.va_humidity.push(val);
            }

            hasNext = !!(logRes.result && logRes.result.has_next && logRes.result.next_row_key);
            rowKey = hasNext ? logRes.result.next_row_key : '';
            pages++;
        }

        const summarize = (arr) => {
            if (!arr.length) return null;
            const sum = arr.reduce((a, b) => a + b, 0);
            return {
                avg: Math.round((sum / arr.length) * 10) / 10,
                min: Math.round(Math.min(...arr) * 10) / 10,
                max: Math.round(Math.max(...arr) * 10) / 10,
                count: arr.length
            };
        };

        return {
            success: true,
            date: dateStr,
            temperature: summarize(readings.va_temperature),
            humidity: summarize(readings.va_humidity)
        };

    } catch (err) {
        console.error('Tuya History fetch failed:', err.stack || err.message, err.apiRaw || '');
        return {
            success: false,
            error: err.message,
            error_code: err.apiCode || null
        };
    }
}

/**
 * Automates the recording of daily logs by backfilling live sensor values.
 * Identifies the active batch and inserts/updates daily records based on East Africa Time (EAT).
 * @param {Object} sensorData - Temperature and humidity logs payload.
 * @returns {Promise<void>}
 */
async function autoFillTodayLog(sensorData) {
    if (!sensorData.temperature && !sensorData.humidity) return;
    try {
        const batchesRows = await allQuery('SELECT data FROM batches');
        const activeBatch = batchesRows
            .map(r => JSON.parse(r.data))
            .find(b => b.status === 'Active');
            
        if (!activeBatch) return;
        
        // Resolve date for East Africa Time (GMT+3 / Nairobi offset)
        const tzOffset = 3 * 60;
        const localDate = new Date(Date.now() + tzOffset * 60 * 1000).toISOString().split('T')[0];
        
        const logRow = await getQuery('SELECT data FROM logs WHERE batch_id = ? AND date = ?', [activeBatch.id, localDate]);
        if (logRow) {
            const log = JSON.parse(logRow.data);
            let updated = false;
            
            if (sensorData.humidity !== null && (log.humidity === null || log.humidity === undefined)) {
                log.humidity = sensorData.humidity;
                updated = true;
            }
            if (sensorData.temperature !== null && (log.temperature === null || log.temperature === undefined)) {
                log.temperature = sensorData.temperature;
                updated = true;
            }
            
            if (updated) {
                await runQuery('UPDATE logs SET data = ? WHERE batch_id = ? AND date = ?', [JSON.stringify(log), activeBatch.id, localDate]);
                console.log(`Tuya Sync: Updated today's log (${localDate}) with temperature: ${log.temperature}°C, humidity: ${log.humidity}%`);
            }
        }
    } catch (e) {
        console.error('Failed to auto-fill today\'s log:', e.message);
    }
}

/**
 * GET /api/sensors/history
 * Retrieves environmental logs history (temperature/humidity) from the last 7 active logs.
 */
app.get('/api/sensors/history', async (req, res) => {
    try {
        const batchesRows = await allQuery('SELECT data FROM batches');
        const activeBatch = batchesRows
            .map(r => JSON.parse(r.data))
            .find(b => b.status === 'Active' || b.status === 'active' || b.status === 'post_batch');

        if (!activeBatch) {
            return res.json([]);
        }

        const rows = await allQuery(
            'SELECT data FROM logs WHERE batch_id = ? ORDER BY date DESC LIMIT 14',
            [activeBatch.id]
        );

        const history = rows
            .map(r => JSON.parse(r.data))
            .filter(l => l.temperature != null || l.humidity != null)
            .slice(0, 7)
            .reverse()
            .map(l => ({
                date: l.date,
                temperature: l.temperature ?? null,
                humidity: l.humidity ?? null
            }));

        res.json(history);
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

/**
 * GET /api/sensors/live
 * Retrieves cached live sensor metrics.
 */
app.get('/api/sensors/live', async (req, res) => {
    try {
        const row = await getQuery('SELECT value FROM entities WHERE key = ?', ['live_sensors']);
        res.json(row ? JSON.parse(row.value) : { success: false, error: 'No sensor data available' });
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

/**
 * GET /api/sensors/tuya-history?date=YYYY-MM-DD
 * Fetches and aggregates Tuya device-reported temperature/humidity for the given date
 * (East Africa Time), for backfilling daily logs that were missed and logged later.
 * Limited to Tuya's free-edition 7-day device log retention.
 */
app.get('/api/sensors/tuya-history', async (req, res) => {
    const date = req.query.date;
    if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
        return res.status(400).json({ success: false, error: 'Query parameter "date" must be in YYYY-MM-DD format' });
    }

    const result = await fetchTuyaSensorHistory(date);
    res.json(result);
});

/**
 * POST /api/sensors/sync
 * Manually commands the server to execute a Tuya synchronization trigger.
 */
app.post('/api/sensors/sync', async (req, res) => {
    try {
        await syncTuyaSensor();
        const row = await getQuery('SELECT value FROM entities WHERE key = ?', ['live_sensors']);
        res.json(row ? JSON.parse(row.value) : { success: false });
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});

/**
 * GET *
 * Catch-all route mapping unhandled requests back to the single-page application index.html.
 */
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

// Start listening and register background sync interval
app.listen(PORT, () => {
    console.log(`Poultry DSS backend running on port ${PORT}`);
    // Sync immediately on boot-up
    syncTuyaSensor();
    // Re-trigger sync loop telemetry every 15 minutes
    setInterval(syncTuyaSensor, 15 * 60 * 1000);
});
